/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as DeliverabilityRouteImport } from './routes/deliverability'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverabilityRoute = DeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/write': typeof WriteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/write': typeof WriteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRoute
  '/write': typeof WriteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/campaigns'
    | '/deliverability'
    | '/engagement'
    | '/insights'
    | '/login'
    | '/playbook'
    | '/write'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/campaigns'
    | '/deliverability'
    | '/engagement'
    | '/insights'
    | '/login'
    | '/playbook'
    | '/write'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/campaigns'
    | '/deliverability'
    | '/engagement'
    | '/insights'
    | '/login'
    | '/playbook'
    | '/write'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  CampaignsRoute: typeof CampaignsRoute
  DeliverabilityRoute: typeof DeliverabilityRoute
  EngagementRoute: typeof EngagementRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  PlaybookRoute: typeof PlaybookRoute
  WriteRoute: typeof WriteRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverability': {
      id: '/deliverability'
      path: '/deliverability'
      fullPath: '/deliverability'
      preLoaderRoute: typeof DeliverabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  CampaignsRoute: CampaignsRoute,
  DeliverabilityRoute: DeliverabilityRoute,
  EngagementRoute: EngagementRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  PlaybookRoute: PlaybookRoute,
  WriteRoute: WriteRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
