/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as DeliverabilityRouteImport } from './routes/deliverability'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverabilityRoute = DeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deliverability': typeof DeliverabilityRoute
  '/engagement': typeof EngagementRoute
  '/insights': typeof InsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/deliverability'
    | '/engagement'
    | '/insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaigns' | '/deliverability' | '/engagement' | '/insights'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/deliverability'
    | '/engagement'
    | '/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  DeliverabilityRoute: typeof DeliverabilityRoute
  EngagementRoute: typeof EngagementRoute
  InsightsRoute: typeof InsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverability': {
      id: '/deliverability'
      path: '/deliverability'
      fullPath: '/deliverability'
      preLoaderRoute: typeof DeliverabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  DeliverabilityRoute: DeliverabilityRoute,
  EngagementRoute: EngagementRoute,
  InsightsRoute: InsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
